### PR TITLE
Add core patches for Postgres v12

### PR DESCRIPTION
**Pull request by ololobus**

### CODE REVIEW

**Comment by maksm90** [comment]
Hi @ololobus ! Thanks for your pull request. Please, try to synchronize custom_signals_12.0.patch with version from [-hackers mail list](https://www.postgresql.org/message-id/37a48ac6-aa14-4e36-5f08-cf8581fe1382%40gmail.com).

**Comment by ololobus** [comment]
Done

**Comment by ololobus** [comment]
Lol, how it get less coverage without any code/tests changes? =)

**Comment by maksm90** [comment]
Thanks, pushed!

**Pull request merged**
